server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${hoodgo.datasource.driver-class-name}
      url: jdbc:mysql://${hoodgo.datasource.host}:${hoodgo.datasource.port}/${hoodgo.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${hoodgo.datasource.username}
      password: ${hoodgo.datasource.password}
    redis:
      host: ${hoodgo.redis.host}
      port: ${hoodgo.redis.port}
      database: ${hoodgo.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hoodgo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      hoodgo:
        mapper: debug
        service: info
        controller: info

hoodgo:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: hustcs
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  alioss:
    endpoint: ${hoodgo.alioss.endpoint}
    access-key-id: ${hoodgo.alioss.access-key-id}
    access-key-secret: ${hoodgo.alioss.access-key-secret}
    bucket-name: ${hoodgo.alioss.bucket-name}


