hoodgo:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: hoodgo_db
    username: root
    password: 123456

  wechat:
    appid: wx7b20c8510392562b
    secret: dab50647313251e453a97b7c3d7fd4eb

  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:

  redis:
    host: localhost
    port: 6379
    database: 0